// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * IPC で返すエラー（05 §2 の `AppError`）。
 */
export type AppError = { code: ErrorCode, message: string, detail?: string, retryable: boolean, };
