// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedItem } from "./FailedItem";
import type { SkippedItem } from "./SkippedItem";

/**
 * 一括操作の結果。
 */
export type BatchResult = { succeeded: number, skipped: Array<SkippedItem>, failed: Array<FailedItem>, };
