// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchResult } from "./BatchResult";

export type BatchFinished = { jobId: string, result: BatchResult, };
