// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchFinished } from "./BatchFinished";
import type { BatchProgress } from "./BatchProgress";

/**
 * 一括操作（削除・移動・クラス変更）の進捗と結果。
 */
export type BatchEvent = { "event": "progress", "data": BatchProgress } | { "event": "finished", "data": BatchFinished };
