// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Versioning } from "./Versioning";

/**
 * バケットの情報（リージョン・バージョニング・暗号化）。
 */
export type BucketInfo = { bucket: string, region: string, versioning: Versioning, encryption: string, 
/**
 * HeadBucket の応答（301 と `x-amz-bucket-region`）から接続のリージョンを修正した（01 §6.1）。
 */
regionCorrected: boolean, };
