// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Versioning } from "./Versioning";

/**
 * バケットの情報（リージョン・バージョニング・暗号化）。
 */
export type BucketInfo = { bucket: string, region: string, versioning: Versioning, encryption: string, };
