// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * リスト表示の列の幅（px）。名前の列は残りの幅を使うため持たない（03 §5.4）。
 */
export type ColumnWidths = { modified: number, size: number, kind: number, storageClass: number, };
