// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同名の項目の扱い（DLG-08）。
 */
export type ConflictDecision = "replace" | "skip" | "keepBoth";
