// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialInput } from "./CredentialInput";

/**
 * 接続の入力値（SCR-01 ステップ 2、DLG-05）。
 */
export type ConnectionInput = { bucket: string, region: string, credential: CredentialInput, roleArn?: string, externalId?: string, };
