// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostTag } from "./CostTag";
import type { StorageClass } from "./StorageClass";

/**
 * 登録済みの接続（表示用）。
 */
export type Connection = { id: string, bucket: string, region: string, regionLabel: string, regionShort: string, credentialId: string, accessKeyIdMasked: string, roleArn: string | null, externalId: string | null, useSourceIdentity: boolean, costTag: CostTag | null, defaultStorageClass: StorageClass | null, };
