// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Versioning } from "./Versioning";

/**
 * 接続の確認結果（04 §2.2）。
 */
export type ConnectionTestResult = { accountId: string, callerArn: string, region: string, regionCorrected: boolean, versioning: Versioning, };
