// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostTag } from "./CostTag";
import type { StorageClass } from "./StorageClass";

/**
 * 接続ごとの設定の変更（設定ウィンドウのコスト配分タグなど）。
 */
export type ConnectionPatch = { costTag?: CostTag | null, defaultStorageClass?: StorageClass | null, useSourceIdentity?: boolean, };
