// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * コストの対象範囲（Q4）。
 */
export type CostScope = { "kind": "tag", key: string, value: string, } | { "kind": "accountRegion", region: string, };
