// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostBreakdown } from "./CostBreakdown";
import type { CostScope } from "./CostScope";

/**
 * Cost Explorer から取得したコスト（04 §13）。
 */
export type CostSummary = { scope: CostScope, 
/**
 * 対象月（例: 2026-09）。
 */
month: string, monthToDate: number, prevMonthSamePeriod: number | null, breakdown: CostBreakdown, 
/**
 * 当月の日数分。未来日は null。
 */
daily: Array<number | null>, forecastMonthEnd: number | null, currency: 'USD', fetchedAt: string, };
