// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 作成日の決め方（04 §9.2）。
 */
export type CreatedSource = "oldestVersion" | "metadata" | "lastModified";
