// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 認証情報の指定（新しいアクセスキー、または既存の認証情報）。
 */
export type CredentialInput = { "kind": "new", accessKeyId: string, secretAccessKey: string, } | { "kind": "existing", credentialId: string, };
