// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 既存の認証情報（DLG-05 の選択肢）。
 */
export type CredentialSummary = { id: string, accessKeyIdMasked: string, 
/**
 * この認証情報を使う接続のバケット名。
 */
usedBy: Array<string>, };
