// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictDecision } from "./ConflictDecision";

/**
 * 同名の項目ごとの決定、またはすべてに同じ決定。
 */
export type Decisions = { all: ConflictDecision, } | { [key in string]: ConflictDecision };
