// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DestinationKeyword } from "./DestinationKeyword";

/**
 * ダウンロードの保存先（既定のダウンロード先、または選択したフォルダ）。
 */
export type DownloadDestination = DestinationKeyword | { selectionId: string, };
