// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropPosition } from "./DropPosition";

/**
 * Finder からのドラッグ中（`dragdrop://enter`／`over`／`leave`）。
 */
export type DragPayload = { position: DropPosition | null, names: Array<string>, };
