// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropPosition } from "./DropPosition";

/**
 * ドロップされた（`dragdrop://drop`）。パスは Rust 側で保管済み。
 */
export type DropPayload = { selectionId: string, position: DropPosition, names: Array<string>, };
