// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreState } from "./RestoreState";
import type { StorageClass } from "./StorageClass";

/**
 * 一覧の項目（05 §2）。
 */
export type Entry = { "type": "folder", key: string, name: string, lastModified: string | null, deleted: boolean, } | { "type": "file", key: string, name: string, size: number, lastModified: string, etag: string, storageClass: StorageClass, restore: RestoreState, deleted: boolean, };
