// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アップロードから除外した理由（04 §4.4）。
 */
export type ExcludeReason = "symlink" | "ignored" | "keyTooLong" | "invalidChar" | "unreadable";
