// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

export type FileFailed = { jobId: string, name: string, error: AppError, };
