// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ファイル種別（02 §8.2）。
 */
export type FileKind = "image" | "video" | "audio" | "pdf" | "sheet" | "archive" | "code" | "doc";
