// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * フォルダの項目数と合計サイズ。
 */
export type FolderSummary = { itemCount: number, totalBytes: number, 
/**
 * 列挙の上限（10 万件）に達した。
 */
truncated: boolean, };
