// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appearance } from "./Appearance";

export type GeneralSettings = { appearance: Appearance, 
/**
 * null は `~/Downloads`。
 */
downloadDir: string | null, showHidden: boolean, showMenuBarIcon: boolean, };
