// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { IndexStatus } from "./IndexStatus";

export type IndexEvent = { "event": "progress", "data": { jobId: string, scanned: number, } } | { "event": "finished", "data": { jobId: string, status: IndexStatus, } } | { "event": "failed", "data": { jobId: string, error: AppError, } };
