// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexStatus } from "./IndexStatus";

/**
 * 背景でのインデックス更新の完了（`index://updated`）。
 */
export type IndexUpdated = { connectionId: string, status: IndexStatus, };
