// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexState } from "./IndexState";

/**
 * 検索インデックスの状態。
 */
export type IndexStatus = { state: IndexState, objectCount: number, lastScanAt: string | null, sizeBytes: number, 
/**
 * 作成中の走査済み件数。
 */
progress: number | null, };
