// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ジョブの状態（01 §6.2、04 §14.1）。
 */
export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "canceled";
