// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一覧の取得条件。
 */
export type ListOptions = { showHidden: boolean, includeDeleted: boolean, };
