// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";

/**
 * 一覧の 1 ページ。
 */
export type ListPage = { entries: Array<Entry>, nextToken: string | null, };
