// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 前回表示していた場所（03 §2）。
 */
export type Location = { connectionId: string, prefix: string, };
