// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppView } from "./AppView";

/**
 * アプリのメニューバーの有効・無効を決める状態（03 §9.4）。
 */
export type MenuState = { view: AppView, 
/**
 * 選択している項目の数。
 */
selectionCount: number, 
/**
 * 選択に取り出していないアーカイブを含む。
 */
hasArchived: boolean, canGoBack: boolean, canGoForward: boolean, canGoUp: boolean, inspectorVisible: boolean, filtersVisible: boolean, showHidden: boolean, showDeleted: boolean, 
/**
 * 表示モード（`list`／`grid`）。
 */
viewMode: string, };
