// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageClass } from "./StorageClass";

/**
 * オブジェクトのバージョン。
 */
export type ObjectVersion = { versionId: string, isLatest: boolean, isDeleteMarker: boolean, lastModified: string, size: number | null, storageClass: StorageClass | null, etag: string | null, };
