// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatedInfo } from "./CreatedInfo";
import type { RestoreState } from "./RestoreState";
import type { StorageClass } from "./StorageClass";

/**
 * オブジェクトのメタデータ（HeadObject）。
 */
export type ObjectDetail = { key: string, versionId: string | null, size: number, contentType: string, lastModified: string, created: CreatedInfo, etag: string, storageClass: StorageClass, encryption: string, kmsKeyId: string | null, checksums: { [key in string]: string }, userMetadata: { [key in string]: string }, restore: RestoreState, };
