// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceSource } from "./PriceSource";
import type { StorageClass } from "./StorageClass";

/**
 * GB・月あたりの単価（04 §13.3）。
 */
export type PriceTable = { region: string, perGbMonth: { [key in StorageClass]?: number }, source: PriceSource, asOf: string, };
