// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 移動先・アップロード先の同名の項目。
 */
export type RemoteConflict = { key: string, remoteSize: number, remoteModified: string, };
