// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アーカイブの取り出し速度（DLG-07）。
 */
export type RestoreTier = "expedited" | "standard" | "bulk";
