// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アーカイブの取り出し状態（04 §8.4）。
 */
export type RestoreState = { "state": "notArchived" } | { "state": "archived" } | { "state": "inProgress" } | { "state": "restored", expiry: string, };
