// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アーカイブの取り出し完了（`restore://completed`）。
 */
export type RestoreCompleted = { connectionId: string, key: string, };
