// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexStatus } from "./IndexStatus";
import type { SearchEntry } from "./SearchEntry";

export type SearchResult = { entries: Array<SearchEntry>, total: number, index: IndexStatus, };
