// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateFilter } from "./DateFilter";
import type { FileKind } from "./FileKind";
import type { SizeFilter } from "./SizeFilter";
import type { Sort } from "./Sort";
import type { StorageClass } from "./StorageClass";

/**
 * 検索条件（04 §10.2）。
 */
export type SearchQuery = { text: string, kind?: FileKind, ext?: string, size?: SizeFilter, date?: DateFilter, storageClass?: StorageClass, sort: Sort, offset: number, limit: number, };
