// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entry } from "./Entry";

/**
 * 検索結果の項目（親フォルダのパスを併記する）。
 */
export type SearchEntry = { entry: Entry, parent: string, };
