// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchSettings = { 
/**
 * インデックスを自動更新するまでの時間（0 は手動のみ）。
 */
autoRefreshMinutes: number, };
