// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionItem } from "./SelectionItem";

export type Selection = { selectionId: string, items: Array<SelectionItem>, };
