// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ファイル選択・ドロップで得たローカルの項目（05 §3.9）。パスはフロントエンドに渡さない。
 */
export type SelectionItem = { name: string, size: number, isDir: boolean, };
