// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { CostSettings } from "./CostSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { SearchSettings } from "./SearchSettings";
import type { TransferSettings } from "./TransferSettings";
import type { ViewSettings } from "./ViewSettings";

/**
 * IPC で受け渡すアプリ設定。
 */
export type Settings = { general: GeneralSettings, view: ViewSettings, transfer: TransferSettings, cost: CostSettings, search: SearchSettings, advanced: AdvancedSettings, };
