// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortKey } from "./SortKey";

export type Sort = { key: SortKey, 
/**
 * 1 は昇順、-1 は降順。
 */
dir: 1 | -1, };
