// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserSession } from "./UserSession";

/**
 * 起動時に一度だけ知らせること（SQLite の作り直しなど）。
 */
export type StartupInfo = { session: UserSession | null, dbRecreated: boolean, version: string, };
