// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSource } from "./MetricsSource";
import type { StorageClass } from "./StorageClass";

/**
 * クラス別の容量とオブジェクト数（04 §12.2）。
 */
export type StorageMetrics = { source: MetricsSource, asOf: string | null, totalBytes: number, objectCount: number | null, byClass: { [key in StorageClass]?: number }, };
