// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 変更先として扱う 7 クラスと、それ以外（`OTHER`）（04 §8.1）。
 */
export type StorageClass = "STANDARD" | "INTELLIGENT_TIERING" | "STANDARD_IA" | "ONEZONE_IA" | "GLACIER_IR" | "GLACIER" | "DEEP_ARCHIVE" | "OTHER";
