// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageClass } from "./StorageClass";

export type TransferSettings = { maxFiles: number, maxPartsPerFile: number, multipartThresholdMb: number, defaultStorageClass: StorageClass, normalizeNfc: boolean, ignore: Array<string>, notifyOnComplete: boolean, };
