// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";
import type { TransferKind } from "./TransferKind";

/**
 * 転送ジョブ（ユーザーの 1 回の操作）。
 */
export type TransferJob = { jobId: string, kind: TransferKind, connectionId: string, title: string, status: JobStatus, totalFiles: number, doneFiles: number, failedFiles: number, totalBytes: number, doneBytes: number, currentName: string | null, bytesPerSec: number, etaSec: number | null, 
/**
 * 転送先の表示（「{バケット}/{プレフィックス}」または保存先フォルダ名）。
 */
destination: string, };
