// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileFailed } from "./FileFailed";
import type { TransferJob } from "./TransferJob";

export type TransferEvent = { "event": "jobUpdated", "data": TransferJob } | { "event": "fileFailed", "data": FileFailed };
