// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新のダウンロードの進捗（`app_install_update` のチャネル）。
 */
export type UpdateEvent = { "event": "progress", "data": { downloaded: number, total: number | null, } } | { "event": "installed" };
