// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新の情報（`app_check_update`）。
 */
export type UpdateInfo = { version: string, notes: string | null, };
