// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExcludedItem } from "./ExcludedItem";
import type { UploadConflict } from "./UploadConflict";

/**
 * アップロードの計画（04 §4.1）。
 */
export type UploadPlan = { planId: string, fileCount: number, totalBytes: number, conflicts: Array<UploadConflict>, excluded: Array<ExcludedItem>, 
/**
 * バケットのバージョニングが有効か（DLG-08 の説明文）。
 */
versioningEnabled: boolean, };
