// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * サインイン中の Google アカウント（05 §2）。
 */
export type UserSession = { sub: string, email: string, name: string, 
/**
 * アバターに表示する頭文字。
 */
initial: string, };
