// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectVersion } from "./ObjectVersion";

export type VersionPage = { versions: Array<ObjectVersion>, nextCursor: string | null, };
