// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * バケットのバージョニング状態。
 */
export type Versioning = "enabled" | "suspended" | "disabled" | "unknown";
