// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sort } from "./Sort";
import type { ViewMode } from "./ViewMode";

export type ViewSettings = { mode: ViewMode, sort: Sort, inspector: boolean, 
/**
 * サイドバーの幅（px）。
 */
sidebarWidth: number, };
